name: libasserest_http
description: HTTP(S) assertion library for Asserest platform for IO and web platform.
version: '1.0.0-beta.1'
repository: https://github.com/Asserest/libasserest_http
environment: 
  sdk: ">2.18.999 <4.0.0"
dependencies:
  libasserest_interface: '>=1.0.0-beta.2 <2.0.0'
  http: ^0.13.5
  meta: ^1.8.0
dev_dependencies: 
  test: ^1.23.1
