name: libasserest_http
description: HTTP(S) assertion library for Asserest platform for IO and web platform.
version: '1.0.0'
repository: https://github.com/Asserest/libasserest_http
environment: 
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  libasserest_interface: ^1.0.0
  http: ^1.1.0
  meta: ^1.9.1
  async_task: ^1.0.20
dev_dependencies: 
  test: ^1.24.2
