name: Test
on:
    push:
        branches: 
            - main
        paths:
            - lib/**.dart
            - test/**.dart
            - pubspec.yaml
            - .github/workflows/test.yml
    pull_request: 
        branches:
            - main
jobs:
    dart-test:
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - macos-latest
                    - windows-latest
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Init Dart
              uses: dart-lang/setup-dart@v1
              with:
                sdk: stable
            - name: Install depenedncies
              run: dart pub get
            - name: Test
              run: dart test
